#!/usr/bin/env npx tsx

/**
 * Morning Briefing Workflow
 *
 * Generates a daily briefing by invoking Claude with context from all integrations.
 * The briefing includes:
 * - Today's calendar overview
 * - Urgent emails and Slack messages
 * - Active incidents and follow-ups
 * - Team availability (out of office)
 * - Outstanding todos
 */

import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { notifyBriefingReady } from '../../packages/shared/src/notify.js';
import { getDateString, getTimestamp, runClaudeCommand } from '../../packages/shared/src/workflow-utils.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = join(__dirname, '../..');

const OUTPUT_DIR = join(PROJECT_ROOT, 'output/briefings');
const LOGS_DIR = join(PROJECT_ROOT, 'logs');

// Ensure directories exist
mkdirSync(OUTPUT_DIR, { recursive: true });
mkdirSync(LOGS_DIR, { recursive: true });

const BRIEFING_PROMPT = `You are an executive assistant for the Director of Engineering. Generate a concise morning briefing for today.

Please gather information and create a briefing with the following sections:

## 📅 Today's Schedule
- List today's calendar events with times and attendees
- Highlight any meetings that need preparation
- Note any focus time blocks

## 📬 Communications
- Check for urgent/important emails that need attention
- Review any unread Slack DMs or important channel mentions
- List any GitHub PRs awaiting my review

## 🚨 Incidents & Operations
- List any active incidents from Incident.io
- Note any outstanding incident follow-ups assigned to me or my team
- Highlight any resolved incidents from the past 24 hours

## 👥 Team
- Who is out of office today (from Humaans)
- Any new hires starting this week
- Upcoming 1:1s that need preparation

## ✅ Priority Tasks
- List my top priority todos for today
- Include any blockers or dependencies

## 💡 Quick Actions
- Suggest 2-3 quick wins I could accomplish today
- Note any decisions I need to make

Format the briefing as clean markdown. Be concise - this should be scannable in under 2 minutes.
Focus on actionable information and things that need my attention today.`;

async function generateBriefing(): Promise<void> {
  const dateString = getDateString();
  const timestamp = getTimestamp();
  const outputFile = join(OUTPUT_DIR, `briefing-${dateString}.md`);
  const logFile = join(LOGS_DIR, `briefing-${timestamp}.log`);

  console.log(`Generating morning briefing for ${dateString}...`);

  try {
    // Check if briefing already exists for today
    if (existsSync(outputFile)) {
      console.log(`Briefing already exists for ${dateString}: ${outputFile}`);
      console.log('Use --force to regenerate.');
      if (!process.argv.includes('--force')) {
        notifyBriefingReady(outputFile);
        return;
      }
      console.log('Regenerating...');
    }

    // Run Claude with the briefing prompt
    const briefingContent = await runClaudeCommand(BRIEFING_PROMPT, { cwd: PROJECT_ROOT });

    // Add header with metadata
    const fullBriefing = `# Morning Briefing - ${dateString}

Generated: ${new Date().toLocaleString()}

---

${briefingContent}

---
*Generated by Apolitical Assistant*
`;

    // Write the briefing
    writeFileSync(outputFile, fullBriefing, 'utf-8');
    console.log(`Briefing saved to: ${outputFile}`);

    // Log the run
    writeFileSync(logFile, JSON.stringify({
      date: dateString,
      timestamp: new Date().toISOString(),
      outputFile,
      success: true,
    }, null, 2), 'utf-8');

    // Send notification
    notifyBriefingReady(outputFile);

  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    console.error('Failed to generate briefing:', errorMessage);

    // Log the error
    writeFileSync(logFile, JSON.stringify({
      date: dateString,
      timestamp: new Date().toISOString(),
      error: errorMessage,
      success: false,
    }, null, 2), 'utf-8');

    process.exit(1);
  }
}

// Run the workflow
generateBriefing().catch((error) => {
  console.error('Fatal error:', error);
  process.exit(1);
});
